### ISSUE TITLE
User can only register for one project and one location

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/pyguess#17]
E.g. if Luís is registered in iGUESS then he can not register in iGUESS-SL.

**Comment by uleopold** [comment]
There should be a possibility that a user can register for multiple projects but that the system sees this user as different ones per project and location, e.g. Luís can register for iGUESS and iGUESS-SL separately. In this case Luís registered at iGUESS Rotterdam is not equal to Luís registered at IGUESS-SL Rotterdam. Also, registration would be done with the same email address, Luis@email.address.

Can the system treat these users as separate users when ID is username + project + location or we would have different user DBs for each project?
