### ISSUE TITLE
Registered datasets are being shown as unregistered

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/pyguess#3]
If I use this server address in the mass_import page:
http://maps.iguess.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/LB_localOWS_test.map

It lists all datasets as unregistered (pink background), but most of them are actually registered and listed in Registered Datasets page (main Data Manager list).

**Comment by ldesousa** [comment]
Only the datasets for the current city should be shown.

**Comment by zajdaf** [comment]
Duplicate of #2
