### ISSUE TITLE
Date Registered now shown properly in Data Manager

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/pyguess#4]
The main Data Manager list is showing "Date_created?" in the Registered field.

**Comment by uleopold** [comment]
Just a comment: if it should show Date Registered I would call the variable rather date_registered instead of date_created as these are 2 different things and one might want to distinguish between the too later in metadata. Date_created would be another metadata entry.

**Comment by ldesousa** [comment]
What variable is this? Perhaps that should be a different issue?

**Comment by uleopold** [comment]
The variable above *"Date_created?"* seems to return the date *registered* , not the date *created*. This variable *date_created* could be renamed to *date_registered* as it should return the date a data set is registered (not created), if I understand it correctly.
