### ISSUE TITLE
Automatic pull in the server is no longer working

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/pyguess#56]
The server is now showing a very old version of pygues. Must investigate why.

**Comment by uleopold** [comment]
It would be good to establish the same concept as we had for iGUESS before. Test is updated on a nightly basis and the production version only on a demand.Subject: [pyguess] Automatic pull in the server is no longer working (#56)The server is now showing a very old version of pygues. Must investigate why.

**Comment by ldesousa** [comment]
That is how it was working when I went on holidays....

**Comment by ldesousa** [comment]
The version in the server diverged from the master branch (not clear why). There were also a few files owned by root messing up the pull. 

There is now a log file for the pull script in logs/pull.log
