### ISSUE TITLE
Data Manager: "Registered Datasets" and "Register Datasets" show data sets of all instances

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/pyguess#60]
* In the Data Manager  **Registered Datasets** shows data sets of all instances. It should show only data sets per location and instance.

![selection_337](https://cloud.githubusercontent.com/assets/1353359/9875345/85123656-5bad-11e5-96c5-38e93dad5634.png)

* When registering new datastes, **Register Datasets** shows registered data sets from all instances after loading web service URL.

![selection_335](https://cloud.githubusercontent.com/assets/1353359/9875291/1dcf267a-5bad-11e5-9d62-9718c9475431.png)

**Comment by ldesousa** [comment]
Actually, it should be showing only the datasets contained in the current Workspace. There is already a session variable with current workspace accessible in the views.

**Comment by mdlux** [comment]
The current workspace is correctly detected, problem is: datasets associated to workspace in data_dataset_workspaces are wrong

**Comment by ldesousa** [comment]
I took a look at the data_dataset_workspaces table and could not find anything outright misplaced. Could you explain what exactly is wrong?

**Comment by mdlux** [comment]
For example workspace id=6 , which is referring to project id=1 (MUSIC) but is linked to datasets for Lamilo (for example: 15, 17, and others)

**Comment by ldesousa** [comment]
There are over 550 datasets registered at this moment. Of these, about 20 are associated to more than one workspace, which is perfectly valid. For instance, the dataset with the id 18 (landuse_obs) is associated to 5 different workspaces in 4 different projects:

pyguess=> ﻿SELECT d.id,
pyguess->    d.identifier as dataset,
pyguess->        l.name as location,
pyguess->        p.name as project,
pyguess->        w.name as workspace
pyguess->   FROM test.data_dataset d,
pyguess->        test.core_location l,
pyguess->        test.core_project p,
pyguess->        test.core_workspace w,
pyguess->        test.data_dataset_workspaces dw,
pyguess->        test.core_project_location pl
pyguess->  WHERE dw.dataset_id = d.id
pyguess->    AND dw.workspace_id = w.id
pyguess->    AND w.proj_location_id = pl.id
pyguess->    AND pl.project_id = p.id
pyguess->    AND pl.location_id = l.id
pyguess->    AND d.id = 18;
 id |   dataset   |     location     |  project   | workspace 
----+-------------+------------------+------------+-----------
 18 | landuse_obs | Luxembourg       | MUSIC      | Public
 18 | landuse_obs | Esch-sur-Alzette | MUSIC      | Public
 18 | landuse_obs | Luxembourg       | LaMiLo     | Public
 18 | landuse_obs | Luxembourg       | LIST       | Public
 18 | landuse_obs | GD Luxembourg    | Ecosystems | Public
(5 rows)

This data reflects the original registrations in the Rails database. There the landuse_obs dataset is actually registered 6 times:

music=> SELECT id, identifier, city_id FROM iguess_dev.datasets WHERE identifier LIKE 'landuse_obs';
  id  | identifier  | city_id 
------+-------------+---------
 2774 | landuse_obs |      27
 2509 | landuse_obs |      20
 3106 | landuse_obs |      14
 2071 | landuse_obs |      11
 3460 | landuse_obs |      26
 1432 | landuse_obs |       8
(6 rows)

Note that even though these registrations may not make sense, there is no way to control or limit where a dataset is registered (and now associated to a workspace). For instance, there is no way to avoid a user registering a dataset from Rotterdam at the Luxembourg location in the LaMiLo project.

For now I would suggest to leave the database as it is and then correct these registration/associations by hand once the Workspace management functionality is in place. 

Regarding the original issue, considering the small number of layers in these conditions, these awkward associations are unlikely to be the cause.

**Comment by uleopold** [comment]
Agreed. It was only important to check that iGUESS displayes the data sets correctly as they are regsitered in the data base. Since we are sure now that everything is displayed as it is registered in the data base we can close this issue.
