### ISSUE TITLE
Data Manager: Mass Import - Registered datasets are shown for all instances.

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/pyguess#69]
When registering a new data set the server response shows the datasets from all instances and not the datasets for the current workspace - location - instance only, i.e. Public - Luxembourg - Smart City Energy (iguess.list.lu). 

Below, in the first screenshot we can see data sets from iguess.list.lu ecosystems.list.lu, iguess-sl.list.lu. The second screenshot displayes the data sets which are actually registered for Luxembourg - Smart City Energy (iguess.list.lu) only.

***Current result of registered data sets according to mass import***
![workspace 1_349](https://cloud.githubusercontent.com/assets/1353359/9930894/4e51509e-5d37-11e5-96b6-9b5871f59655.png)

***Correct result of registered data sets for Smart City Energy in the Data Manager table***
![workspace 1_350](https://cloud.githubusercontent.com/assets/1353359/9930963/c064dc6e-5d37-11e5-90fb-03ff76d6e9a2.png)

**Comment by ldesousa** [comment]
It is no longer possible to register a dataset twice has it happened in the Rails application. When some sort of workspace management page is available, it will then possible to associate registered datasets with a workspace.

**Comment by ldesousa** [comment]
The registered datasets shown in the mass_import template are now restricted to the current workspace. This may cause some unexpected behaviours.
