### ISSUE TITLE
Maps page: layer stack is upside down

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/pyguess#71]
![layerstack](https://cloud.githubusercontent.com/assets/1137878/9933971/ded64108-5d4e-11e5-8e42-ff02a61f401b.png)

The vector should be on top in this example.

**Comment by MStefas** [comment]
It seems you doesn't use the last version , the look&feel seems different from here: 
![image](https://cloud.githubusercontent.com/assets/7814178/9934499/1fced546-5d52-11e5-82d5-ad237d521d2f.png)

And the layers catalogue elements are in "always" alphabetical order for now. The slider order should be the same as the corresponding layers on the map

**Comment by ldesousa** [comment]
The layer stack seems to be upside down in the second picture too.

**Comment by MStefas** [comment]
Seen with Luis, all is ok
