### ISSUE TITLE
Maps: Remove arrows from drop down in  Base Layers

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/pyguess#78]
Unless there is  a good reason, I would remove the arrows in Base Layers, see screenshot below. 

![selection_351](https://cloud.githubusercontent.com/assets/1353359/9988320/c02285ce-604f-11e5-9161-9250b69f717f.png)

**Comment by MStefas** [comment]
There's no good reason, and It was fixed in a previous commit. Maybe the master branch isn't up to date with the ol3 branch

**Comment by uleopold** [comment]
pre {display: block;font-family: Helvetica Neue, Helvetica, Arial, sans-serif;white-space: pre-wrap;margin: 1em 0;}Great. This might be the case then. 

Sent from IBM VerseStefas Mickaël --- Re: [pyguess] Maps: Remove arrows from drop down in  Base Layers (#78) --- From:"Stefas Mickaël" <notifications@github.com>To:"ERIN-LIST/pyguess" <pyguess@noreply.github.com>Cc:"Ulrich Leopold" <ulrich.leopold@list.lu>Date:Mon, 21 Sep 2015 14:20Subject:Re: [pyguess] Maps: Remove arrows from drop down in  Base Layers (#78)There's no good reason, and It was fixed in a previous commit. Maybe the master branch isn't up to date with the ol3 branch

**Comment by MStefas** [comment]
![image](https://cloud.githubusercontent.com/assets/7814178/9995589/1fae8ef6-6083-11e5-884c-38083caca6d0.png)
