### ISSUE TITLE
Maps: Swipe

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/pyguess#87]
test the implemenation of Swipe
http://openlayers.org/en/v3.9.0/examples/layer-swipe.html?q=

**Comment by uleopold** [comment]
Hi Mickaël, you can put the swipe slider underneath the map as in the examples page. It is more intuitive to use it  that way as you directly swipe at the position of the mouse.

**Comment by MStefas** [comment]
Done on develop branch, but I'm still disappointed by the "mouse coordinate" position (visible on the screenshot).

![image](https://cloud.githubusercontent.com/assets/7814178/10971215/741ce67c-83d3-11e5-8982-86ba8e210f48.png)

**Comment by uleopold** [comment]
pre {display: block;font-family: Helvetica Neue, Helvetica, Arial, sans-serif;white-space: pre-wrap;margin: 1em 0;}Maybe increase the footer of the map so we can show the coordinates above. Wenn anyway still also need in the footer of the map the scale drop down. See old iguess.list.lu/maps 

Sent from IBM Verse
Stefas Mickaël --- Re: [pyguess] Maps: Swipe (#87) --- From:"Stefas Mickaël" <notifications@github.com>To:"ERIN-LIST/pyguess" <pyguess@noreply.github.com>Cc:"Ulrich Leopold" <ulrich.leopold@list.lu>Date:Thu, 5 Nov 2015 15:42Subject:Re: [pyguess] Maps: Swipe (#87)Done on develop branch, but I'm still disappointed by the "mouse coordinate" position (visible on the screenshot).
