### ISSUE TITLE
Maps: Identify - Pop up window style

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/pyguess#89]
Test if identify can use a pop up as displayed in the example below is feasible.
http://openlayers.org/en/v3.9.0/examples/popup.html?q=

**Comment by MStefas** [comment]
Well, this is already handled, but I have to correctly display the gml object inside it.

![image](https://cloud.githubusercontent.com/assets/7814178/10043832/55de2904-61f6-11e5-851f-74384726acb4.png)

**Comment by MStefas** [comment]
Now the identify feature work correctly. We have to define its final look :)
![image](https://cloud.githubusercontent.com/assets/7814178/10102768/8ef0d5f6-63a0-11e5-8e87-7b7f0850574b.png)

**Comment by MStefas** [comment]
Now display also feature information for layers under the top one :) (done while fixing issues #102 and #101)

**Comment by MStefas** [comment]
Feature informations are also sorted by layer position. And the layer name is also displayed in feature info . I've also removed the bounding box information, as they weren't displayed in previous iGuess.

![image](https://cloud.githubusercontent.com/assets/7814178/10514273/29cf52e4-734d-11e5-835a-d1e06d653d98.png)
