### ISSUE TITLE
Modules: "Module type" selector is fetching the wrong parameters

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/pyguess#9]
When creating a new Configuration, the selector "Module type" is fetching the wrong inputs. For instance, if I select "Sums numbers." I am presented with the UHI inputs.

![config](https://cloud.githubusercontent.com/assets/1137878/8646011/a5ce10f6-294c-11e5-9d0a-6ac63dcad8cc.png)

**Comment by zajdaf** [comment]
Seems correct

**Comment by ldesousa** [comment]
This issue is back. Also happening when clicking in "Create new configuration for this service" in the Module Catalogue.

![configurationparams](https://cloud.githubusercontent.com/assets/1137878/8926267/bdcaa6a6-350e-11e5-8172-49299ffd9eeb.png)
