### ISSUE TITLE
Maps: Rotation of maps

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/pyguess#90]
Test the implementation of map rotation
http://openlayers.org/en/v3.9.0/examples/rotation.html?q=rotation

**Comment by uleopold** [comment]
In fact the functionality comes out of the box and is already there. 

We only need the button with the arrow showing up to put the map back into North direction. You can try the feature in PyGUESS with alt+shift + drag with mouse (left button).

See top left icon on the map in screenshot below. Code here 
http://openlayers.org/en/v3.10.1/examples/rotation.html

![selection_387](https://cloud.githubusercontent.com/assets/1353359/10941572/5c822ca6-830c-11e5-9235-e1d309e17fd7.png)

**Comment by MStefas** [comment]
Done on develop branch:
![image](https://cloud.githubusercontent.com/assets/7814178/10970897/a7026b4a-83d1-11e5-9568-71c4b447a0fc.png)
