### ISSUE TITLE
Maps: Auto-expand maping window to bottom of screen

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/pyguess#94]
When in full screen mode with the browser the mapping window should expand to bottom of screen. Maybe that is also an issue with the general layout?
---------------------------------------------------8<---------------------------------------------------------------------------
![workspace 1_353](https://cloud.githubusercontent.com/assets/1353359/10080206/a684cfd6-62ee-11e5-9e55-6232e75f9854.png)
--------------------------------------------------8<-----------------------------------------------------------------------------

**Comment by MStefas** [comment]
Yes it is an issue of the general layout. 2 things are needed to fix it: automatically compute the size on the content of each page, depending of the screen size, and let the footer of the page being a bootstrap footer, as here: http://getbootstrap.com/examples/sticky-footer/

**Comment by MStefas** [comment]
Should be ok with the last commit, but only on branch ol3 for now
