### ISSUE TITLE
Footer too sticky on all pages and does not adapt

### ISSUE THREAD

**Issue by uleopold** [ERIN-LIST/pyguess#99]
We now have suddenly this situation of a very sticky footer which does not adapt to the screen an all pages. we now have scroll bars showing up.

I would prefer that the footer moves further down and we can see the body of the page instead of having a sticky footer which forces scroll bars.

Just if there is white space underneath the footer it move to the bottom of the page.

***Full screen view with scroll bar on the left hand side.***
![workspace 1_369](https://cloud.githubusercontent.com/assets/1353359/10186774/bc23fc5c-6764-11e5-999b-08998f0ee474.png)

**Comment by uleopold** [comment]
Mickaël, Maël could you have a a briefl look at this and see if you can modify this as I would like to show the platform tomorrow and like this it is not very useable. I do not know if someone changed something to make it appear like this?

Maybe also see if you can reproduce this. I use the iguess-django site.

**Comment by MStefas** [comment]
This is probably due to a change I made yesterday. It is strange because it was made to allow the page to be automatically fit the screen size, and It worked with chrome and firefox. In case the content is too big, then a scroll bar appears to let the user see what is missing, so the header (menu) and the footer are always displayed. 

Can you just give me your screen resolution ? 

I propose two ways to fix this:

- Let only the header and the content part be fit the screen size, so the footer won't be always displayed.
- Give as minimum height for the content a sufficient height for the home page

What do you prefer ? Or maybe you prefer something else ? I'll do the first solution as a start

**Comment by uleopold** [comment]
pre {display: block;font-family: Helvetica Neue, Helvetica, Arial, sans-serif;white-space: pre-wrap;margin: 1em 0;}First solution is a good start. My screen is 1080 x 800, I think. 

Sent from IBM VerseStefas Mickaël --- Re: [pyguess] Footer too sticky on all pages and does not adapt (#99) --- From:"Stefas Mickaël" <notifications@github.com>To:"ERIN-LIST/pyguess" <pyguess@noreply.github.com>Cc:"Ulrich Leopold" <ulrich.leopold@list.lu>Date:Wed, 30 Sep 2015 12:18Subject:Re: [pyguess] Footer too sticky on all pages and does not adapt (#99)This is probably due to a change I made yesterday. It is strange because it was made to allow the page to be automatically fit the screen size, and It worked with chrome and firefox. In case the content is too big, then a scroll bar appears to let the user see what is missing, so the header (menu) and the footer are always displayed. 

Can you just give me your screen resolution ? 

I propose two ways to fix this:


Let only the header and the content part be fit the screen size, so the footer won't be always displayed.
Give as minimum height for the content a sufficient height for the home page


What do you prefer ? Or maybe you prefer something else ? I'll do the first solution as a start

**Comment by MStefas** [comment]
And what is your browser ? Chrome ? Firefox ? Which version ?

**Comment by uleopold** [comment]
pre {display: block;font-family: Helvetica Neue, Helvetica, Arial, sans-serif;white-space: pre-wrap;margin: 1em 0;}Firefox and chromium latest production versions on Linux. Dont exact ones right now. 

Sent from IBM VerseStefas Mickaël --- Re: [pyguess] Footer too sticky on all pages and does not adapt (#99) --- From:"Stefas Mickaël" <notifications@github.com>To:"ERIN-LIST/pyguess" <pyguess@noreply.github.com>Cc:"Ulrich Leopold" <ulrich.leopold@list.lu>Date:Wed, 30 Sep 2015 12:41Subject:Re: [pyguess] Footer too sticky on all pages and does not adapt (#99)And what is your browser ? Chrome ? Firefox ? Which version ?

**Comment by MStefas** [comment]
I restored the old sizing comportment on all page, and for map page I now give at least a 400px height to the content panel, if more is available, I give the full available size, so to see the footer you will have to scroll down on the map page.

Is it correct for you ? The server has been updated
